<a href="https://colab.research.google.com/github/Shifana4303/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python

#array collection of data with same datatype(homogenious)

a=np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [ ]:


a=np.array([1,2,3.0,4])

a

array([1., 2., 3., 4.])

In [ ]:


a=np.array([1,2,3.0,4,"a"])

print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing-forward slicing backward slicing

b=np.array([1,2,3,4,5])
#print 1,2
b[0:2]
#print 5,4
b[-1:-3:-1]
#print 4,5
b[3:]
#print 2,1
b[-4::-1]

array([2, 1])

In [ ]:
#dimension

a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4]])
a.ndim  #dimension=1   vector
b.ndim  #dimension =2  matrix
print(b)
print(a)
b.shape


[[1 2]
 [3 4]]
[0 2 3 4 5]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3,
                     #4,5


z=np.array([[2,3],[4,5]])
print(z)

print(z.shape)
print(z.ndim)
print(z.size)  #total no. of elements in matrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print shape,size,diamension


z=np.array([[1,2,3],[4,5,6]])
print(z)
print(z.shape)
print(z.size)
print(z.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [ ]:
#create a 4x2 matrix display size,shape,dimension

z=np.array([[1,2],[3,4],[5,6],[7,8]])
print(z)
print(z.shape)
print(z.size)
print(z.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
8
2


In [ ]:
#create a 4x4 matrix

a=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[1,5,6,7]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [1 5 6 7]]
(4, 4)
16
2


In [ ]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[1,5,6,7]])
z[0]
z[:,0]                 #z[row,column]
z[1,1]
z[2,2]
z[3,2:]
z[2:,2:]
z[1:3,3]
z[1:3,0:3]
z[0:3,1:]
z[1:,0:]
z[0:,1]
z[0:,0:]                 #z

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [1, 5, 6, 7]])

In [ ]:
#zero matrix

#z=np.zeros([3,3,3])
#z
#z=np.zeros([3,3,3],dtype=int)
#z
z=np.zeros([3,3,3],dtype=complex)           #complex means a+ip format
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
#one matrix

z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create a 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition

print(a+b)

#matrix substraction

print(a-b)

#matrix multiplication

print(a*b)  #not a matrix multiplication

print(a@b)
print(a.dot(b))  #matrix multiplication

#matrix division

print(a/b)

[[ 4  3]
 [ 9 11]]
[[-2  1]
 [-3 -3]]
[[ 3  2]
 [18 28]]
[[15 15]
 [33 31]]
[[15 15]
 [33 31]]
[[0.33333333 2.        ]
 [0.5        0.57142857]]


MAGIC means -have two underscore eg: __ add__

In [ ]:
#FULL MATRIX

a=np.full([3,3],7,dtype=int)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#create a 3x4 matrix with value 9 and datatype complex

z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix
a=np.identity((3),dtype=int)
a

a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a 4x4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,3,2,7],[2,1,9,6]])
print(y)
print(y.size)

[[1 2 3 4]
 [5 6 7 8]
 [9 3 2 7]
 [2 1 9 6]]
16


In [ ]:
a=y.reshape(16,1)
a
a=y.reshape(8,2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 3],
       [2, 7],
       [2, 1],
       [9, 6]])

In [ ]:
#arange

a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix with float values

a=np.array([[2.5,3.4,5.5],[7.1,2.9,3.1],[8.9,4.5,6.7]])
a

array([[2.5, 3.4, 5.5],
       [7.1, 2.9, 3.1],
       [8.9, 4.5, 6.7]])

In [ ]:
#floor

z=np.floor(a)
z

array([[2., 3., 5.],
       [7., 2., 3.],
       [8., 4., 6.]])

In [ ]:
#ceil

z=np.ceil(a)
z

array([[3., 4., 6.],
       [8., 3., 4.],
       [9., 5., 7.]])

In [ ]:
#round

z=np.round(a)
z                          #incase of .5 round towards even[even-back,odd-front eg:2.5=2,3.5=4]

array([[2., 3., 6.],
       [7., 3., 3.],
       [9., 4., 7.]])

In [10]:
#create a 3x3 matrix

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])                       #in numpy=axis=1 -> row
a                                                           #In numpy=axis=0 ->column
a.max()
a.max(axis=1)
a.max(axis=0)

a.min()
a.min(axis=1)
a.min(axis=0)
print(a.sum(axis=1))

a.sum(axis=0)
np.sqrt(a)
np.sin(a)
np.cos(a)
np.tan(a)

#flatten

a.flatten()                                              #it get as one by one(one dimension)

[ 6 15 24]


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [13]:
#sort
#create a 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)
b=np.sort(a,axis=0)
b=np.sort(a,axis=1)

print(b)
c=np.argsort(a,axis=1)       #arg=index
                             #argsort=index based sorting
print(c)

[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[1 3 4]
 [1 3 5]
 [6 8 9]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
